GET http://localhost:8080/api/issue/token
Accept: application/json
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3b25iaW5AbWFpbC5jb20iLCJleHAiOjE2NjU2Nzk1OTcsImlhdCI6MTY2NTY2OTU5N30.VrAbI37jKCzlkDP8xGWVZq3aL8qwao9OZSFs-mMzz4s

###
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname": "jasun123",
  "pw": "@Qlqjs134",
  "pwck" : "@Qlqjs134"
}

###
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname": "jasun1234",
  "pw": "@Qlqjs134",
  "pwck" : "@Qlqjs134"
}

###
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname": "jasun123",
  "pw": "@Qlqjs134"
}

###
POST http://localhost:8080/api/post
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjM0MTQ0NSwiaWF0IjoxNjY2MzM5NjQ1fQ.cm3ZIw-zcnVqXuqcGiRSUuDAwhryVHPe41MSQAGQ05g


{
  "title" : "test1",
  "contents": "contents1"
}

### ㄱㅔ시글 작성
POST http://localhost:8080/api/post
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjA5NjIzNSwiaWF0IjoxNjY2MDk0NDM1fQ.LkymMENd1Vl1Xw_njUf0e9BqMpJD20_p0Z1KGxPBK-M


{
  "title": "title",
  "contents": "contents"
}

###
PUT http://localhost:8080/api/post/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjI2ODQ4NiwiaWF0IjoxNjY2MjY2Njg2fQ.HQSHpTSfghoh1HwEGtYmeHC34aDPEimoSBuQVH5hCuU


{
  "contents": "내용수정!111"
}

###
DELETE http://localhost:8080/api/post/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE3NTg0OCwiaWF0IjoxNjY2MTc0MDQ4fQ.yr76KEghZH9j7zcbgIWm4kl0xjYZbtt3_D_NeW3WZCI

###
GET http://localhost:8080/api/show
Content-Type: application/json

###
GET http://localhost:8080/api/show/1
Content-Type: application/json

###
POST http://localhost:8080/api/post/1/comment
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE5NzE4OSwiaWF0IjoxNjY2MTk1Mzg5fQ.XhDpxVGjAgOhp9_8DsIx5KK_mvJFFHAmdgI49v7pPoY

{
  "comment": "댓글!234"
}

###
POST http://localhost:8080/api/like/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE4NDc4NiwiaWF0IjoxNjY2MTgyOTg2fQ.-o-pT_U3rEwdxOiVJKDDiLzp_Oxhiu5FHTBg8XuainE


###
DELETE http://localhost:8080/api/like/1
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE4NDc4NiwiaWF0IjoxNjY2MTgyOTg2fQ.-o-pT_U3rEwdxOiVJKDDiLzp_Oxhiu5FHTBg8XuainE

###
GET http://localhost:8080/api/mypage/like
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjA5NjIzNSwiaWF0IjoxNjY2MDk0NDM1fQ.LkymMENd1Vl1Xw_njUf0e9BqMpJD20_p0Z1KGxPBK-M

###
GET http://localhost:8080/api/mypage/post
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE3MDQ4MSwiaWF0IjoxNjY2MTY4NjgxfQ.ZwkXOXmKdT9Tu6KTwjtuEFz-1DUWcpaIIEF_tDsT7Cw

###
GET http://localhost:8080/api/mypage/comment
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMyIsImV4cCI6MTY2NjE3MjUyMywiaWF0IjoxNjY2MTcwNzIzfQ.chZIBM14Vk9lKQ8l89fzEQbm-l9bfPjiu2vv9yd4ZP4






###  회원가입
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname": "jasun1234",
  "pw": "@Qlqjs134",
  "pwck" : "@Qlqjs134"
}

### 로그인
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname": "jasun1234",
  "pw": "@Qlqjs134"
}

### 게시글 작성
POST http://localhost:8080/api/post
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMzQiLCJleHAiOjE2NjY0MzExOTQsImlhdCI6MTY2NjQzMTEzNH0.wwT1SB-MbRM8VNoM5tKr4DkBih2faFesLi6n4OoeeYU
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyMzQiLCJleHAiOjE2NjY0MzExNzIsImlhdCI6MTY2NjQzMTA1Mn0.nuqSU_M-O_7wKb0frPCf5jqmTRnRQCdvMxU3jLHyxx4


{
  "title" : "test1",
  "contents": "contents1"
}