###
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "nickname": "jasun12",
  "password": "Qlqjs134",
  "passwordConfirm" : "Qlqjs134"
}

###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "nickname": "jasun12",
  "password": "Qlqjs134"
}

###
POST http://localhost:8080/addpost
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

{
  "title" : "test1",
  "content": "contents1"
}

###
PUT http://localhost:8080/post/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

{
  "title": "수정",
  "content": "내용수정222"
}

###
DELETE http://localhost:8080/post/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

###
GET http://localhost:8080/show/post
Content-Type: application/json

###
GET http://localhost:8080/show/4
Content-Type: application/json

###
POST http://localhost:8080/post/4/comment
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

{
  "comment": "댓글!234"
}

###
PUT http://localhost:8080/post/4/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

{
  "comment": "댓글!5554"
}

###
DELETE http://localhost:8080/post/4/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

###
POST http://localhost:8080/like/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE

###
DELETE http://localhost:8080/like/4
Content-Type: application/json
Access_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXN1bjEyIiwiZXhwIjoxNjY2MjAwNDQ0LCJpYXQiOjE2NjYxOTk4NDR9.CHtAEXmU7DXwH4Gwy1V-1tbzf6VLmOJeB4qWNahVDZE
