spring :
#  profiles:
#    include: aws
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://springboot-database.cv9x8k0pldzz.ap-northeast-2.rds.amazonaws.com:3306/myselectshop?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
#    password: rb3080qja

  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    properties:
      hibernate:
        format_sql: true
        show_sql: ture

jwt:
  secret : 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk